stages:
  build:
    node_label: python
    steps:
      - echo "build"
  publish:
    node_label: python
    steps:
      - echo "publish"
  deploy:
    node_label: python
    steps:
      - echo "deploy"
