stages:
  build:
    node_label: python
    steps:
      - make test
  publish:
    node_label: kaniko-deployer
    steps:
      - make publish
  deploy:
    node_label: jetstream-deployer
    steps:
      - echo "Nothing to deploy!"
